// GENERATED by scripts/build-manifest.cjs — do not edit by hand.
// Regenerated on every dev/build run; reflects what is actually in public/.

export type FrameSequence = { count: number; ext: string; pad: number };

export const FRAME_SEQUENCES: Record<string, FrameSequence> = {
  "munition": {
    "count": 250,
    "ext": "webp",
    "pad": 4
  },
  "scout": {
    "count": 150,
    "ext": "webp",
    "pad": 4
  }
};

export const VIDEOS: readonly string[] = [
  "scout-terrain-1",
  "scout-terrain-2",
  "scout-tracking",
  "scout-working"
];

export const POSTERS: readonly string[] = [
  "scout-terrain-1",
  "scout-terrain-2",
  "scout-tracking",
  "scout-working"
];

export const IMAGES: readonly string[] = [
  "photo-munition.jpg",
  "photo-scout.jpg"
];
